Django Code/gs67/gs67/urls.py
from django.contrib import admin
from django.urls import path
from enroll import views
urlpatterns = [
    path('admin/', admin.site.urls),
    path('signup/', views.sign_up, name='signup'),
    path('login/', views.user_login, name='login'),
    path('dashboard/', views.user_dashboard, name='dashboard'),
    path('logout/', views.user_logout, name='logout'),
]

Django Code/gs67/enroll/models.py
from django.db import models

# Create your models here.
class Blog(models.Model):
 title = models.CharField(max_length=100)
 desc = models.CharField(max_length=200)

Django Code/gs67/enroll/forms.py
from django.contrib.auth.models import User
from django import forms
from django.contrib.auth.forms import UserCreationForm, UserChangeForm

class SignUpForm(UserCreationForm):
 password2 = forms.CharField(label='Confirm Password (again)', widget=forms.PasswordInput)
 class Meta:
  model = User
  fields = ['username', 'first_name', 'last_name', 'email']
  labels = {'email': 'Email'}

class EditUserProfileForm(UserChangeForm):
 password = None
 class Meta:
  model = User
  fields = ['username', 'first_name', 'last_name', 'email', 'date_joined', 'last_login']
  labels = {'email': 'Email'}

class EditAdminProfileForm(UserChangeForm):
 password = None
 class Meta:
  model = User
  fields = '__all__'
  labels = {'email': 'Email'}

Django Code/gs67/enroll/views.py
from django.shortcuts import render, HttpResponseRedirect
from .forms import SignUpForm, EditUserProfileForm, EditAdminProfileForm
from django.contrib import messages
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth import authenticate, login, logout, update_session_auth_hash
from django.contrib.auth.models import User, Group

# Signup View Function
def sign_up(request):
 if request.method == "POST":
  fm = SignUpForm(request.POST)
  if fm.is_valid():
   messages.success(request, 'Account Created Successfully !!') 
   user = fm.save()
   group = Group.objects.get(name='Editor')
   user.groups.add(group)
 else: 
  fm = SignUpForm()
 return render(request, 'enroll/signup.html', {'form':fm})

# Login View Function
def user_login(request):
  if not request.user.is_authenticated:
    if request.method == "POST":
      fm = AuthenticationForm(request=request, data=request.POST)
      if fm.is_valid():
        uname = fm.cleaned_data['username']
        upass = fm.cleaned_data['password']
        user = authenticate(username=uname, password=upass)
        if user is not None:
          login(request, user)
          messages.success(request, 'Logged in successfully !!')
          return HttpResponseRedirect('/dashboard/')
    else: 
      fm = AuthenticationForm()
    return render(request, 'enroll/userlogin.html', {'form':fm})
  else:
    return HttpResponseRedirect('/dashboard/')

# Dahsboard
def user_dashboard(request):
  if request.user.is_authenticated:
    return render(request, 'enroll/dashboard.html', {'name':request.user.username})
  else:
    return HttpResponseRedirect('/login/')

# Logout
def user_logout(request):
  logout(request)
  return HttpResponseRedirect('/login/')

Django Code/gs67/enroll/templates/enroll/dashboard.html
<!DOCTYPE html>
<html lang="en">
<head>
 <meta charset="UTF-8">
 <meta name="viewport" content="width=device-width, initial-scale=1.0">
 <title>Dashboard</title>
</head>
<body>
 <h1>Dashboard Page</h1>
  <h2>Welcome {{name}}</h2>

{% if perms.enroll.delete_blog %}
  <input type="button" value="Delete"> <br><br>
{% else %}
  <h3>No Delete Permission</h3>
{% endif %}

{% if perms.enroll.add_blog %}
  <input type="button" value="Add"> <br><br>
{% else %}
  <h3>No Add Permission</h3>
{% endif %}


 <a href="{% url 'logout' %}">Logout</a>
</body>
</html>

Django Code/gs67/enroll/templates/enroll/signup.html
<!DOCTYPE html>
<html lang="en">
<head>
 <meta charset="UTF-8">
 <meta name="viewport" content="width=device-width, initial-scale=1.0">
 <title>User Registration</title>
 <style>
  .success{
   color:red;
  }
 </style>
</head>
<body>
<form action="" method="post" novalidate>
 {% csrf_token %}
  {% if form.non_field_errors %}
   {% for error in form.non_field_errors %}
    <p class="er">{{error}}</p>
   {% endfor %}
  {% endif %}
 {% for fm in form %}
  {{fm.label_tag}} {{fm}} {{fm.errors|striptags}} <br><br>
 {% endfor %}
 <input type="submit" value="Submit">
</form>
{% if messages %}
 {% for message in messages %}
  <small {% if message.tags %} class="{{message.tags}}" {% endif %}> {{message}} </small>
 {% endfor %}
 {% endif %}
 <a href="{% url 'login' %}">Login</a>
</body>
</html>

Django Code/gs67/enroll/templates/enroll/userlogin.html
<!DOCTYPE html>
<html lang="en">
<head>
 <meta charset="UTF-8">
 <meta name="viewport" content="width=device-width, initial-scale=1.0">
 <title>User Login</title>
 <style>
 .er{
  color:red;
 }
 </style>
</head>
<body>
 <form action="" method="post" novalidate>
  {% csrf_token %}
  {% if form.non_field_errors %}
   {% for error in form.non_field_errors %}
    <p class="er">{{error}}</p>
   {% endfor %}
  {% endif %}
  {% for fm in form %}
   {{fm.label_tag}} {{fm}} {{fm.errors|striptags}} <br><br>
  {% endfor %}
  <input type="submit" value="Login">
 </form>
  <a href="{% url 'signup' %}">Signup</a>
</body>
</html>